on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://34.134.137.212:8080"
        user: "jenkins"
        token: ${{ secrets.TOKEN }}
        job: "DeployPROD"
